import type { Transaction } from "@/entities/transaction/model/types";

export const mockRecentTransactions: Transaction[] = [
  {
    id: "txn-1",
    occurredAt: "2026-07-09T05:12:00Z",
    description: "스타벅스 강남점",
    amountMinor: 6_500,
    currency: "KRW",
    direction: "out",
    categoryLabel: "식비",
    reviewStatus: "confirmed",
  },
  {
    id: "txn-2",
    occurredAt: "2026-07-08T23:40:00Z",
    description: "쿠팡",
    amountMinor: 42_900,
    currency: "KRW",
    direction: "out",
    categoryLabel: "쇼핑",
    reviewStatus: "pending",
  },
  {
    id: "txn-3",
    occurredAt: "2026-07-08T09:05:00Z",
    description: "월급 입금",
    amountMinor: 3_200_000,
    currency: "KRW",
    direction: "in",
    categoryLabel: "급여",
    reviewStatus: "confirmed",
  },
  {
    id: "txn-4",
    occurredAt: "2026-07-07T12:31:00Z",
    description: "지하철 정기권",
    amountMinor: 55_000,
    currency: "KRW",
    direction: "out",
    categoryLabel: "교통",
    reviewStatus: "pending",
  },
  {
    id: "txn-5",
    occurredAt: "2026-07-06T14:20:00Z",
    description: "전기요금 자동이체",
    amountMinor: 38_400,
    currency: "KRW",
    direction: "out",
    categoryLabel: "주거/공과금",
    reviewStatus: "confirmed",
  },
];
